services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    ports:
    - "${BROKER_PORT}:${BROKER_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER_USER}
      RABBITMQ_DEFAULT_PASS: ${BROKER_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      start_period: 10s
      timeout: 3s
      retries: 3
  redis:
    image: "redis"
    ports:
    - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      start_period: 5s
      timeout: 3s
      retries: 3
  client:
    build: ./DABClient/
    ports:
    - "${CLIENT_PORT}:3000"
    command: ["npm", "run", "dev"]
    environment:
      PUBLISH_EXCHANGE: "client_messages"
      CONSUME_EXCHANGE: "server_broadcast"
    volumes:
      - ./DABClient:/app
      - /app/node_modules
  server:
    build: ./BackEndServer
    ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      BROKER_URI: "amqp://${BROKER_USER}:${BROKER_PASS}@rabbitmq:${BROKER_PORT}/"
      PUBLISH_EXCHANGE: "server_broadcast"
      CONSUME_EXCHANGE: "client_messages"
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true